# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 60
cpus_per_task: 8
gpus_per_node: 1
tasks_per_node: 1
mem_per_cpu: "2GB"
nodes: 1
name: ${hydra.job.name}
partition: gpu.4h
comment: "NPNF prediction job"
signal_delay_s: 300
gpus: null
